version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: lara-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  
  mysql:
    container_name: lara-mysql
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
     - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAG: dev
      SERVICE_NAME: mysql

    networks:
      - laravel
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: lara-php
    command: bash -c "cp /var/www/html/.env.example .env"
    command: bash -c "php /var/www/html/artisan key:generate"
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
